Int-Byte4/WizBuddy

src/main/java/com/intbyte/wizbuddy/shop/domain/entity/Shop.java
=> create pull request

src/main/java/com/intbyte/wizbuddy/board/domain/entity/ManualBoard.java, src/main/java/com/intbyte/wizbuddy/board/domain/entity/NoticeBoard.java, src/main/java/com/intbyte/wizbuddy/board/domain/entity/SubsBoard.java, src/main/java/com/intbyte/wizbuddy/config/MybatisConfiguration.java, src/main/java/com/intbyte/wizbuddy/mapper/EmployeeMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/EmployerMapper.java, src/main/java/com/intbyte/wizbuddy/shop/domain/entity/Shop.java, src/main/java/com/intbyte/wizbuddy/shop/dto/ShopDTO.java
=> ✨ 기능 추가: ShopDTO

src/main/java/com/intbyte/wizbuddy/board/dto/ManualBoardDTO.java, src/main/java/com/intbyte/wizbuddy/board/dto/NoticeBoardDTO.java, src/main/java/com/intbyte/wizbuddy/board/dto/SubsBoardDTO.java
=> Board domain의 DTO 추가

src/main/java/com/intbyte/wizbuddy/shop/dto/ShopDTO.java
=> ✨ 기능 추가: ShopDTO 추가

src/main/java/com/intbyte/wizbuddy/mapper/ChecklistMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/ManualBoardMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/ShopMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/SubsBoardMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/TaskMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.java, src/main/resources/com/intbyte/wizbuddy/mapper/ChecklistBoard.xml, src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/EmployerMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/ManualBoardMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/ShopMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/SubsBoardMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/TaskMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.xml
=> ✨ 기능 추가: Mybatis Mapper 추가

src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java
코드에 get을 활용해서 중복하는 과정이 있다고 느껴 수정했습니다.
=> ♻️ 코드 수정 : ShopService 매장등록 코드 수정

src/main/java/com/intbyte/wizbuddy/shop/domain/DeleteShopInfo.java, src/main/java/com/intbyte/wizbuddy/shop/domain/entity/Shop.java, src/main/java/com/intbyte/wizbuddy/shop/repository/ShopRepository.java, src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java, src/test/java/com/intbyte/wizbuddy/shop/service/ShopServiceTests.java
close #25 
- 매장 삭제는 사장이 직접 하는 것이 아닌, 관리자에게 요청을 하는 것으로 추후에 추가해야 한다. 그리고 Flag인 boolean 값으로 검색을 할 수 있냐 없냐를 서비스에서 할 수 있게 구현했다.
- 즉, Flag 가 false인 경우 NotFoundException 예외처리가 된다.
- 그리고 테스트 코드는 Flag가 false가 되면 삭제된 것으로 간주하고 DB에는 데이터를 남겨뒀다.
=> ✨ 기능 추가 : 매장 삭제 기능 및 테스트 추가

src/main/java/com/intbyte/wizbuddy/board/domain/entity/ManualBoard.java, src/main/java/com/intbyte/wizbuddy/board/dto/ManualBoardDTO.java, src/main/java/com/intbyte/wizbuddy/board/repository/ManualBoardRepository.java, src/main/java/com/intbyte/wizbuddy/board/service/ManualBoardService.java, src/main/java/com/intbyte/wizbuddy/user/domain/entity/User.java, src/main/java/com/intbyte/wizbuddy/user/dto/UserDTO.java, src/main/resources/com/intbyte/wizbuddy/mapper/ManualBoardMapper.xml, src/test/java/com/intbyte/wizbuddy/board/service/ManualBoardServiceTests.java
=> ✨ 기능 추가 : 매뉴얼 게시글 등록 기능 추가

src/main/java/com/intbyte/wizbuddy/exception/StatusEnum.java, src/main/java/com/intbyte/wizbuddy/exception/task/TaskNotFoundException.java, src/main/java/com/intbyte/wizbuddy/task/domain/EditTaskInfo.java, src/main/java/com/intbyte/wizbuddy/task/domain/entity/Task.java, src/main/java/com/intbyte/wizbuddy/task/service/TaskService.java, src/test/java/com/intbyte/wizbuddy/task/service/TaskServiceTests.java
- EditTaskInfo 클래스 추가
- TaskNotFoundException 예외 추가
- TaskServiceTests 테스트코드 수정
=> 업무 로직 수정 및 테스트코드 수정

src/main/java/com/intbyte/wizbuddy/exception/weeklyschedule/ScheduleNotFoundException.java, src/main/java/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.java, src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/EmployeeWorkingPart.java, src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/WeeklySchedule.java, src/main/java/com/intbyte/wizbuddy/schedule/dto/EmployeeWorkingPartDTO.java, src/main/java/com/intbyte/wizbuddy/schedule/repository/EmployeeWorkingPartRepository.java, src/main/java/com/intbyte/wizbuddy/schedule/repository/WeeklyScheduleRepository.java, src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java, src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.xml, src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
근무일정 조회 기능과 등록 기능을 일부 추가했습니다.
- 예외처리 코드를 추가해 근무일정이 없는 스케줄 코드를 입력하는 경우에 NotFoundException이 발생하도록 하였습니다.
=> 근무일정 조회 기능 및 테스트 코드 추가 + 등록 기능 추가

src/main/java/com/intbyte/wizbuddy/mapper/EmployeeMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/UserAndEmployerMapper.java, src/main/java/com/intbyte/wizbuddy/shop/domain/EditShopInfo.java, src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java, src/main/java/com/intbyte/wizbuddy/user/domain/entity/Employee.java, src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/EmployerMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/ShopMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/UserAndEmployeeMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/UserAndEmployerMapper.xml, src/test/java/com/intbyte/wizbuddy/shop/service/ShopServiceTests.java
유저의 외래키 매핑을 통해 User를 Employer와 Employee로 나눠서 조회 가능하게끔 mapper를 세분화했습니다.
- mapper를 세분화한 부분으로 나눠서 사용하면 좋을 것 같습니다.
=> 유저 외래키 매핑 추가 및 매장 코드 변경

src/main/java/com/intbyte/wizbuddy/checklist/domain/EditCheckListInfo.java, src/main/java/com/intbyte/wizbuddy/checklist/domain/entity/CheckList.java, src/main/java/com/intbyte/wizbuddy/checklist/dto/CheckListDTO.java, src/main/java/com/intbyte/wizbuddy/checklist/repository/CheckListRepository.java, src/main/java/com/intbyte/wizbuddy/checklist/service/CheckListService.java, src/main/java/com/intbyte/wizbuddy/exception/StatusEnum.java, src/main/java/com/intbyte/wizbuddy/exception/checklist/CheckListNotFoundException.java, src/main/java/com/intbyte/wizbuddy/mapper/CheckListMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/ChecklistMapper.java, src/main/java/com/intbyte/wizbuddy/task/service/TaskService.java, src/main/resources/com/intbyte/wizbuddy/mapper/CheckListBoard.xml, src/main/resources/com/intbyte/wizbuddy/mapper/CheckListMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/ChecklistBoard.xml, src/test/java/com/intbyte/wizbuddy/checklist/service/CheckListServiceTests.java, src/test/java/com/intbyte/wizbuddy/task/service/TaskServiceTests.java
기본적인 체크리스트 CRUD 서비스 코드와 테스트하는 메서드를 작성 했습니다.
- 조회 테스트의 경우 assertNotNull 메서드를 사용해 null 여부를 확인하는 테스트코드로 진행했습니다.
close #50 
close #52
=> ✨ 기능 추가 : 체크리스트 CRUD 및 테스트코드 추가

src/main/java/com/intbyte/wizbuddy/mapper/EmployeeMapper.java, src/main/java/com/intbyte/wizbuddy/shop/domain/DeleteShopInfo.java, src/main/java/com/intbyte/wizbuddy/shop/domain/entity/Shop.java, src/main/java/com/intbyte/wizbuddy/user/domain/DeleteEmployeeInfo.java, src/main/java/com/intbyte/wizbuddy/user/domain/DeleteEmployerInfo.java, src/main/java/com/intbyte/wizbuddy/user/domain/EditEmployeeInfo.java, src/main/java/com/intbyte/wizbuddy/user/domain/EditEmployerInfo.java, src/main/java/com/intbyte/wizbuddy/user/domain/entity/Employee.java, src/main/java/com/intbyte/wizbuddy/user/domain/entity/Employer.java, src/main/java/com/intbyte/wizbuddy/user/repository/EmployeeRepository.java, src/main/java/com/intbyte/wizbuddy/user/repository/EmployerRepository.java, src/main/java/com/intbyte/wizbuddy/user/service/EmployeeService.java, src/main/java/com/intbyte/wizbuddy/user/service/EmployerService.java, src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeMapper.xml, src/test/java/com/intbyte/wizbuddy/shop/service/ShopServiceTests.java
- Info 로 수정하거나 삭제할 때 사용할 컬럼만 사용하는 과정을 보는 것이 좋습니다.
테스트는 아직 추가하지 않았습니다.
=> 사장, 직원 - 조회, 수정, 삭제 기능 추가

src/main/java/com/intbyte/wizbuddy/mapper/EmployerMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/UserAndEmployerMapper.java, src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java, src/main/java/com/intbyte/wizbuddy/user/domain/SignInEmployeeInfo.java, src/main/java/com/intbyte/wizbuddy/user/domain/SignInEmployerInfo.java, src/main/java/com/intbyte/wizbuddy/user/domain/SignInUserInfo.java, src/main/java/com/intbyte/wizbuddy/user/dto/EmployeeDTO.java, src/main/java/com/intbyte/wizbuddy/user/service/UserService.java, src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/UserAndEmployerMapper.xml, src/test/java/com/intbyte/wizbuddy/user/service/UserServiceTests.java
- UserAndEmployerMapper.xml 에서 Mybatis로 외래키 매핑을 해 User와 Employer 테이블에 Insert가 각각 가능하게끔 구현했습니다.
=> 유저, 사장 외래키 매핑 추가 및 사장 추가 기능, 테스트 추가

src/main/java/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.java, src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/EmployeeWorkingPart.java, src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/WeeklySchedule.java, src/main/java/com/intbyte/wizbuddy/schedule/dto/EmployeeWorkingPartDTO.java, src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java, src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.xml, src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
=> ✨ 기능 추가: 직원별 근무일정 조회, 근무일 수정, 근무일 삭제 및 테스트 코드 추가

src/main/java/com/intbyte/wizbuddy/comment/domain/Entity/Comment.java, src/main/java/com/intbyte/wizbuddy/comment/dto/CommentDTO.java, src/main/java/com/intbyte/wizbuddy/comment/repository/CommentRepository.java, src/main/java/com/intbyte/wizbuddy/comment/service/CommentService.java, src/main/java/com/intbyte/wizbuddy/mapper/CommentMapper.java, src/main/resources/com/intbyte/wizbuddy/mapper/CommentMapper.xml, src/test/java/com/intbyte/wizbuddy/comment/service/CommentServiceTests.java
---
name: 댓글 조회 기능
about:  댓글 전체 조회가 가능하다.
title: ''
assignees: ''
---
- [✅ ] 신규 기능
- [✅ ] 기능 수정
-  조회 잘 작동 되는지 확인
- [✅  ] 댓글 조회
=> Nahyeon✨ 기능 추가 : Comment 전체 조회 Service, 테스트 기능 추가

src/main/java/com/intbyte/wizbuddy/schedule/domain/EditScheduleInfo.java
=> ✨ 기능 추가: 스케줄 수정 데이터를 담은 EditScheduleInfo 추가

src/main/java/com/intbyte/wizbuddy/comment/service/CommentService.java, src/main/java/com/intbyte/wizbuddy/mapper/CommentMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/EmployerMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/UserAndEmployeeMapper.java, src/main/java/com/intbyte/wizbuddy/user/domain/RegisterEmployeeInfo.java, src/main/java/com/intbyte/wizbuddy/user/domain/RegisterEmployerInfo.java, src/main/java/com/intbyte/wizbuddy/user/service/EmployeeService.java, src/main/java/com/intbyte/wizbuddy/user/service/EmployerService.java, src/main/java/com/intbyte/wizbuddy/user/service/UserService.java, src/main/resources/com/intbyte/wizbuddy/mapper/UserAndEmployeeMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/UserAndEmployerMapper.xml, src/test/java/com/intbyte/wizbuddy/user/service/UserServiceTests.java
---
name: 제훈
about: 직원 유저가 등록할 때는 유저에 등록하면서 직원 유저 데이터도 생성된다.
title: '직원 등록 기능, 테스트 추가'
assignees:
---
=> Jehun ✨ 기능 추가 : 직원 등록 기능 + 테스트 추가

src/main/java/com/intbyte/wizbuddy/shop/domain/RegisterShopInfo.java, src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java, src/test/java/com/intbyte/wizbuddy/shop/service/ShopServiceTests.java
- Info 를 추가하고, controller 생성 시 매장 등록할 때 필요한 매개변수는 매장 정보와 EmployerCode 라고 생각해서 수정했습니다.
=> ♻️ 코드 수정 : 매장 등록용 info 추가로 인한 코드 수정

src/main/java/com/intbyte/wizbuddy/board/domain/DeleteNoticeBoardInfo.java, src/main/java/com/intbyte/wizbuddy/board/domain/EditNoticeBoardInfo.java, src/main/java/com/intbyte/wizbuddy/board/domain/entity/ManualBoard.java, src/main/java/com/intbyte/wizbuddy/board/domain/entity/NoticeBoard.java, src/main/java/com/intbyte/wizbuddy/board/service/NoticeBoardService.java, src/main/java/com/intbyte/wizbuddy/exception/noticeboard/NoticeBoardModifyOtherUserException.java, src/main/java/com/intbyte/wizbuddy/exception/noticeboard/NoticeBoardNotFoundException.java, src/main/java/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.java, src/main/resources/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.xml
---
name: 공지사항 게시판 게시글 수정, 삭제 기능 추가
about: 사장은 공지사항 게시판에서 자신이 작성한 게시글을 수정 또는 삭제할 수 있다.
title: ''
assignees: ''
---
- 테스트 코드 추가 예정
=> 공지사항 게시판 게시글 수정, 삭제 기능 추가

src/main/java/com/intbyte/wizbuddy/schedule/dto/WeeklyScheduleDTO.java, src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java, src/main/resources/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.xml, src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
등록된 근무일정에 직원 배치 기능 추가, 관련 테스트 코드 수정했습니다
=> ✨ 기능 추가: 근무일정에 직원배치 기능 추가 및 테스트코드 수정

src/main/java/com/intbyte/wizbuddy/board/domain/EditSubsBoardInfo.java, src/main/java/com/intbyte/wizbuddy/board/domain/entity/SubsBoard.java, src/main/java/com/intbyte/wizbuddy/board/service/SubsBoardService.java, src/main/java/com/intbyte/wizbuddy/comment/domain/EditCommentInfo.java, src/main/java/com/intbyte/wizbuddy/comment/domain/Entity/Comment.java, src/main/java/com/intbyte/wizbuddy/comment/dto/CommentDTO.java, src/main/java/com/intbyte/wizbuddy/comment/service/CommentService.java, src/main/java/com/intbyte/wizbuddy/exception/StatusEnum.java, src/main/java/com/intbyte/wizbuddy/exception/board/SubsBoardNotFoundException.java, src/main/java/com/intbyte/wizbuddy/exception/comment/CommentNotFoundException.java, src/main/java/com/intbyte/wizbuddy/mapper/CommentMapper.java, src/main/resources/com/intbyte/wizbuddy/mapper/CommentMapper.xml, src/test/java/com/intbyte/wizbuddy/board/service/SubsBoardServiceTests.java, src/test/java/com/intbyte/wizbuddy/comment/service/CommentServiceTests.java
---
name: 댓글 조회, 등록, 수정, 삭제 기능 추가
about: 댓글 조회, 등록, 수정, 삭제가 가능하다.
title: ''
assignees: ''
---
- [ ✅ ] 신규 기능
- [✅ ] 기능 수정
- 댓글을 조회, 등록, 수정, 삭제가 잘 작동 되는가
- [✅ ] 댓글 삭제
- [✅  ] 댓글 등록
- [✅ ] 댓글 수정
- [✅  ] 댓글 기능
close #41 #40 #46 #49 #51 #53 #58 #57 #56 #44
=> ♻️ 코드 수정 : Comment 수정 테스트 refactor

src/main/java/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.java, src/main/java/com/intbyte/wizbuddy/schedule/repository/EmployeeWorkingPartRepository.java, src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java, src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.xml, src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
=> ✨ 기능 추가: 대타 게시판에서 댓글 선택해서 근무일정 수정 기능 추가

src/main/java/com/intbyte/wizbuddy/checklist/domain/CheckListMybatis.java, src/main/java/com/intbyte/wizbuddy/checklist/domain/entity/CheckList.java, src/main/java/com/intbyte/wizbuddy/checklist/service/CheckListService.java, src/main/java/com/intbyte/wizbuddy/mapper/CheckListMapper.java, src/main/resources/com/intbyte/wizbuddy/mapper/CheckListMapper.xml, src/test/java/com/intbyte/wizbuddy/checklist/service/CheckListServiceTests.java
CheckListMybatis 객체를 사용해서 mybatis 활용하도록 수정
checkList 외래키 제약조건에 따른 mybatis select문 수정
=> ✨ 기능 추가 / 수정 CheckList 외래키 제약조건 추가

src/main/java/com/intbyte/wizbuddy/checklist/domain/entity/CheckList.java
shopCode의 어노테이션을 수정했습니다.
(Column -> JoinColumn)
=> ♻ 코드 수정: 체크리스트 엔티티 어노테이션 수정

src/main/java/com/intbyte/wizbuddy/comment/domain/Entity/Comment.java, src/main/java/com/intbyte/wizbuddy/comment/dto/CommentDTO.java, src/test/java/com/intbyte/wizbuddy/comment/service/CommentServiceTests.java
---
name: 댓글 등록 및 코드 refactor
about: 댓글 등록 및 코드 refactor진행했습니다.
title: ''
assignees: ''
---
- [✅ ] 신규 기능
- [✅] 기능 수정
- 댓글이 등록이 잘 작동 되는가 
- [✅] 댓글 등록
close #49
=> ♻️ 코드 수정 : Comment Type 변환 수정

src/main/java/com/intbyte/wizbuddy/board/domain/entity/SubsBoard.java, src/main/java/com/intbyte/wizbuddy/comment/domain/Entity/Comment.java, src/main/java/com/intbyte/wizbuddy/comment/service/CommentService.java, src/test/java/com/intbyte/wizbuddy/comment/service/CommentServiceTests.java
---
name:  Comment 채택 기능 추가
about:  Comment 채택을 실행하면 true로 변환한다.
title: ''
assignees: ''
---
- [✅] 신규 기능
- [✅ ] 기능 수정
- 댓글 채택 시, 상태가 true로 변환이 잘 작동 되는가
- [✅]  댓글 채택 
close #58
=> ✨ 기능 추가 : Comment 채택 기능 추가

src/main/java/com/intbyte/wizbuddy/task/controller/TaskController.java, src/main/java/com/intbyte/wizbuddy/task/dto/TaskDTO.java, src/main/java/com/intbyte/wizbuddy/task/vo/response/ResponseFindTaskVO.java
=> ✨ 기능 추가: Task Controller 추가

src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java, src/main/java/com/intbyte/wizbuddy/task/controller/TaskController.java, src/main/java/com/intbyte/wizbuddy/task/domain/EditTaskInfo.java, src/main/java/com/intbyte/wizbuddy/task/vo/request/RequestInsertTaskVO.java, src/main/java/com/intbyte/wizbuddy/task/vo/request/RequestModifyTaskVO.java, src/main/java/com/intbyte/wizbuddy/task/vo/response/ResponseInsertTaskVO.java, src/main/java/com/intbyte/wizbuddy/task/vo/response/ResponseModifyTaskVO.java
[✨ 기능 추가: TaskController 매핑 완료](https://github.com/Int-Byte4/WizBuddy/commit/4c4cfbbcf7c27c4ef73a38246ae1880376077a49)
=> ✨ 기능 추가: TaskController 매핑 완료

src/main/java/com/intbyte/wizbuddy/user/controller/UserController.java, src/main/java/com/intbyte/wizbuddy/user/service/EmployeeService.java, src/test/java/com/intbyte/wizbuddy/shop/service/ShopServiceTests.java, src/test/java/com/intbyte/wizbuddy/user/service/EmployeeServiceTests.java, src/test/java/com/intbyte/wizbuddy/user/service/EmployerServiceTests.java, src/test/java/com/intbyte/wizbuddy/user/service/UserServiceImplTests.java
✨ 기능 추가 : 직원 조회 기능 추가 및 테스트코드 수정
=> ✨ 기능 추가 : 직원 조회 기능 추가 및 테스트코드 수정

src/main/java/com/intbyte/wizbuddy/user/controller/UserController.java, src/main/java/com/intbyte/wizbuddy/user/service/EmployeeService.java, src/main/java/com/intbyte/wizbuddy/user/service/EmployerService.java, src/main/java/com/intbyte/wizbuddy/user/service/UserServiceImpl.java
=> ✨ 기능 추가 : 직원 추가, 조회 컨트롤러 추가

src/main/java/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.java, src/main/java/com/intbyte/wizbuddy/schedule/domain/EditScheduleInfo.java, src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/EmployeeWorkingPart.java, src/main/java/com/intbyte/wizbuddy/schedule/dto/EmployeeWorkingPartDTO.java, src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java, src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.xml, src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
employeeCode 타입 변경 (int -> String)
employeeCode 타입 변경으로 인해 오류난 관련 코드들 수정
=> ♻ 코드 수정: employeeCode 타입 변경 및 관련 서비스 기능 코드 수정

src/main/java/com/intbyte/wizbuddy/board/controller/SubsBoardController.java, src/main/java/com/intbyte/wizbuddy/board/domain/entity/SubsBoard.java, src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestDeleteSubsBoardVO.java, src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestInsertSubsBoardVO.java, src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestModifySubsBoardVO.java, src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseDeleteSubsBoardVO.java, src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseFindSubsBoardVO.java, src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseInsertSubsBoardVO.java, src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseModifySubsBoardVO.java, src/main/java/com/intbyte/wizbuddy/comment/domain/Entity/Comment.java
---
name: SubsBoard Controller 추가
about: SubsBoard Controller 추가  하였다.
title: ''
assignees: ''
---
- [✅ ] 신규 기능
- [✅ ] 기능 수정
- [✅] SubsBoard Controller 추가
=> ✨ 기능 추가  : SubsBoard Controller 추가

src/main/java/com/intbyte/wizbuddy/board/dto/NoticeBoardDTO.java, src/main/java/com/intbyte/wizbuddy/board/service/ManualBoardService.java, src/main/java/com/intbyte/wizbuddy/board/service/NoticeBoardService.java, src/main/java/com/intbyte/wizbuddy/mapper/ManualBoardMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.java, src/main/resources/com/intbyte/wizbuddy/mapper/ManualBoardMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.xml, src/test/java/com/intbyte/wizbuddy/board/service/ManualBoardServiceTests.java, src/test/java/com/intbyte/wizbuddy/board/service/NoticeBoardServiceTests.java
---
name: 공지사항, 매뉴얼 게시글 전체 조회, 단건 조회 기능 추가
about: 공지사항, 매뉴얼 게시글 전체 또는 하나 조회할 수 있다.
title: ''
assignees: ''
---
=> 공지사항, 매뉴얼 게시글 전체 조회, 단건 조회 기능 및 테스트코드 추가

src/main/java/com/intbyte/wizbuddy/checklist/service/CheckListService.java, src/main/java/com/intbyte/wizbuddy/taskperchecklist/service/TaskPerCheckListService.java, src/test/java/com/intbyte/wizbuddy/taskperchecklist/service/TaskPerCheckListServiceTests.java
=> ♻️ 코드 수정 : TaskPerCheckListService 코드 수정

src/main/java/com/intbyte/wizbuddy/employeepershop/controller/EmployeePerShopController.java, src/main/java/com/intbyte/wizbuddy/employeepershop/domain/entity/EmployeePerShop.java, src/main/java/com/intbyte/wizbuddy/employeepershop/domain/entity/EmployeePerShopId.java, src/main/java/com/intbyte/wizbuddy/employeepershop/repository/EmployeePerShopRepository.java, src/main/java/com/intbyte/wizbuddy/employeepershop/service/EmployeePerShopService.java, src/main/java/com/intbyte/wizbuddy/mapper/EmployeePerShopMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/ShopMapper.java, src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java, src/main/java/com/intbyte/wizbuddy/user/service/UserServiceImpl.java, src/main/resources/com/intbyte/wizbuddy/mapper/EmployeePerShopMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/ShopMapper.xml, src/test/java/com/intbyte/wizbuddy/employeepershop/service/EmployeePerShopServiceTests.java
=> ♻ 코드 수정: ManyToOne 관계 제거

src/main/java/com/intbyte/wizbuddy/board/repository/SubsBoardRepository.java, src/main/java/com/intbyte/wizbuddy/comment/repository/CommentRepository.java, src/main/java/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.java, src/main/java/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.java, src/main/java/com/intbyte/wizbuddy/schedule/controller/ScheduleController.java, src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/EmployeeWorkingPart.java, src/main/java/com/intbyte/wizbuddy/schedule/domain/entity/WeeklySchedule.java, src/main/java/com/intbyte/wizbuddy/schedule/info/EditScheduleInfo.java, src/main/java/com/intbyte/wizbuddy/schedule/repository/EmployeeWorkingPartRepository.java, src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java, src/main/java/com/intbyte/wizbuddy/schedule/vo/response/ResponseFindEmployeeWorkingPartVO.java, src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java, src/main/resources/com/intbyte/wizbuddy/mapper/EmployeeWorkingPartMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/WeeklyScheduleMapper.xml, src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
대타 게시판에 작성한 댓글을 선택해서 스케줄을 수정하는 기능을 추가하였습니다.
=> ✨ 기능 추가: 댓글 채택해서 스케줄 수정 기능 추가

src/main/java/com/intbyte/wizbuddy/schedule/controller/ScheduleController.java, src/main/java/com/intbyte/wizbuddy/schedule/service/ScheduleService.java, src/main/java/com/intbyte/wizbuddy/schedule/vo/request/RequestModifyScheduleByCommentVO.java, src/main/java/com/intbyte/wizbuddy/schedule/vo/response/ResponseModifyScheduleByCommentVO.java, src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java, src/test/java/com/intbyte/wizbuddy/schedule/service/ScheduleServiceTests.java
ScheduleController에 댓글 채택으로 스케줄을 수정하는 기능을 추가하였습니다.
=> ✨ 기능 추가: ScheduleController에 댓글 채택으로 스케줄 수정 기능 추가

src/main/java/com/intbyte/wizbuddy/like/domain/entity/ManualBoardLiked.java, src/main/java/com/intbyte/wizbuddy/like/domain/entity/NoticeBoardLiked.java, src/main/java/com/intbyte/wizbuddy/like/dto/ManualBoardLikedDTO.java, src/main/java/com/intbyte/wizbuddy/like/dto/NoticeBoardLikedDTO.java, src/main/java/com/intbyte/wizbuddy/like/repository/ManualBoardLikedRepository.java, src/main/java/com/intbyte/wizbuddy/like/repository/NoticeBoardLikedRepository.java, src/main/java/com/intbyte/wizbuddy/like/service/ManualBoardLikedService.java, src/main/java/com/intbyte/wizbuddy/like/service/NoticeBoardLikedService.java, src/main/resources/com/intbyte/wizbuddy/mapper/ManualBoardLikedMapper.xml, src/main/resources/com/intbyte/wizbuddy/mapper/NoticeBoardLikedMapper.xml, src/test/java/com/intbyte/wizbuddy/board/service/ManualBoardLikedServiceTests.java, src/test/java/com/intbyte/wizbuddy/board/service/NoticeBoardLikedServiceTests.java
---
name: ✨ 기능 수정  : 게시글 좋아요 기능 수정
about: 게시글 좋아요 기능  폴더 기능 분할
title: ''
assignees: ''
---
=> ✨ 기능 수정  : 게시글 좋아요 기능 수정

src/main/java/com/intbyte/wizbuddy/board/controller/ManualBoardController.java, src/main/java/com/intbyte/wizbuddy/board/controller/NoticeBoardController.java, src/main/java/com/intbyte/wizbuddy/board/domain/DeleteNoticeBoardInfo.java, src/main/java/com/intbyte/wizbuddy/board/domain/entity/NoticeBoard.java, src/main/java/com/intbyte/wizbuddy/board/dto/NoticeBoardDTO.java, src/main/java/com/intbyte/wizbuddy/board/service/ManualBoardService.java, src/main/java/com/intbyte/wizbuddy/board/service/NoticeBoardService.java, src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestInsertNoticeBoardVO.java, src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestUpdateNoticeBoardVO.java, src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseFindNoticeBoardVO.java, src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseInsertNoticeBoardVO.java, src/main/java/com/intbyte/wizbuddy/board/vo/response/ResponseUpdateNoticeBoardVO.java, src/main/java/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.java, src/main/resources/com/intbyte/wizbuddy/mapper/NoticeBoardMapper.xml, src/test/java/com/intbyte/wizbuddy/board/service/NoticeBoardServiceTests.java
---
name: 공지사항 게시판 controller 추가
about: 공지사항 게시판 컨트롤러 추가
title: ''
assignees: ''
---
=> ✨ 기능 추가 : 공지사항 게시판 controller 추가

src/main/java/com/intbyte/wizbuddy/board/controller/SubsBoardController.java, src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestInsertManualBoardVO.java, src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestInsertSubsBoardVO.java, src/main/java/com/intbyte/wizbuddy/board/vo/request/RequestModifySubsBoardVO.java, src/main/java/com/intbyte/wizbuddy/like/controller/ManualBoardLikeController.java, src/main/java/com/intbyte/wizbuddy/like/controller/NoticeBoardLikeController.java, src/main/java/com/intbyte/wizbuddy/like/domain/entity/ManualBoardLiked.java, src/main/java/com/intbyte/wizbuddy/like/domain/entity/NoticeBoardLiked.java, src/main/java/com/intbyte/wizbuddy/like/service/ManualBoardLikedService.java, src/main/java/com/intbyte/wizbuddy/like/service/NoticeBoardLikedService.java, src/main/java/com/intbyte/wizbuddy/like/vo/request/RequestInsertManualBoardLikeVO.java, src/main/java/com/intbyte/wizbuddy/like/vo/request/RequestInsertNoticeBoardLikeVO.java, src/main/java/com/intbyte/wizbuddy/like/vo/response/ResponseInsertManualBoardLikeVO.java, src/main/java/com/intbyte/wizbuddy/like/vo/response/ResponseInsertNoticeBoardLikeVO.java, src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java, src/test/java/com/intbyte/wizbuddy/board/service/SubsBoardServiceTests.java, src/test/java/com/intbyte/wizbuddy/comment/service/CommentServiceTests.java, src/test/java/com/intbyte/wizbuddy/like/service/ManualBoardLikedServiceTests.java, src/test/java/com/intbyte/wizbuddy/like/service/NoticeBoardLikedServiceTests.java
---
name:  Like 등록 요청, 응답 기능 추가
about: 공지사항과 매뉴얼 게시글의 좋아요 등록 기능 요청 및 응답 처리 RestAPI 기능 추가 
title: ''
assignees: ''
---
- [✅ ] 신규 기능
- [✅ ] 기능 수정
-  좋아요 등록 요청과 응답이 Postman으로 잘 작동이 되는지 확인
- [✅] 좋아요 등록 Controller
=> ✨ 기능 추가 : Like 등록 요청, 응답 RestAPI 기능 추가

src/main/java/com/intbyte/wizbuddy/employeepershop/controller/EmployeePerShopController.java, src/main/java/com/intbyte/wizbuddy/employeepershop/service/EmployeePerShopService.java, src/main/java/com/intbyte/wizbuddy/mapper/ShopMapper.java, src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java, src/main/resources/com/intbyte/wizbuddy/mapper/ShopMapper.xml
불필요한 employee 관련 코드 수정 및 컨트롤러 매핑 수정
=> ♻️ 코드 수정: shop 관련 코드 수정

src/main/java/com/intbyte/wizbuddy/schedule/controller/ScheduleController.java
=> ✨ 기능 추가: Swagger Operation 추가

src/main/java/com/intbyte/wizbuddy/board/controller/ManualBoardController.java, src/main/java/com/intbyte/wizbuddy/checklist/controller/CheckListController.java, src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java, src/main/java/com/intbyte/wizbuddy/task/controller/TaskController.java, src/main/java/com/intbyte/wizbuddy/taskperchecklist/controller/TaskPerCheckListController.java
=> ✨ 기능 추가: swagger 설정 완료

src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java, src/main/java/com/intbyte/wizbuddy/shop/controller/ShopController.java, src/main/java/com/intbyte/wizbuddy/shop/service/ShopService.java, src/main/java/com/intbyte/wizbuddy/user/controller/UserController.java, src/main/java/com/intbyte/wizbuddy/user/service/EmployeeService.java, src/main/java/com/intbyte/wizbuddy/user/service/EmployerService.java
=> ♻️ 코드 수정: shop, user 관련 코드 수정

wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/repository/SubsBoardRepository.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/service/InfraAdoptServiceImpl.java, wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/comment/infrastructure/service/InfraAdoptServiceImplTests.java
---
name: ✨ 기능 수정: 댓글 채택 및 스케줄 코드 수정 기능 테스트 수정
about: 댓글 채택 및 스케줄 코드 수정 기능 테스트 수정
title: ''
assignees: ''
---
- [✅ ] 기능 수정
-  댓글 채택 및 스케줄 코드 수정 기능 테스트 수정 이 잘 되었는가
- [✅ ] 댓글 채택 및 스케줄 코드 수정 기능 테스트 수정
=> ✨ 기능 수정: 댓글 채택 및 스케줄 코드 수정 기능 테스트 수정

wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/repository/EmployeeWorkingPartRepository.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/service/InfraAdoptServiceImpl.java
---
name: 코드 수정 및 기능 추가
about: 댓글 채택해서 스케줄 수정 기능 예외처리 수정
---
- 기존에 같은 값을 비교하던 문제를 해결했습니다.
=> ♻️✨ 코드 수정 및 기능 추가: 댓글 채택해서 스케줄 수정 기능 예외처리 수정

wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/command/application/controller/CheckListController.java, wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/query/controller/CheckListController.java, wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/command/application/controller/TaskController.java, wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/command/infrastructure/client/ShopServiceClient.java, wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/query/controller/TaskController.java, wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/command/application/controller/TaskPerCheckListController.java, wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/query/config/MybatisConfiguration.java, wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/query/controller/TaskPerCheckListController.java, wizbuddy-task-service/src/main/resources/com/intbyte/wizbuddy/taskperchecklist/query/repository/TaskPerCheckListMapper.xml
=> ♻️ 코드 수정 : taskService Bean name 설정 및 코드 수정

wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/controller/EmployeeWorkingPartController.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartService.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartServiceImpl.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/domain/aggregate/vo/response/ResponseRegistEmployeeVO.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/command/application/controller/WeeklyScheduleController.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/command/application/service/WeeklyScheduleService.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/command/application/service/WeeklyScheduleServiceImpl.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/command/domain/aggregate/vo/response/ResponseRegistWeeklyScheduleVO.java, wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartServiceImplTests.java, wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/weeklyschedule/command/application/service/WeeklyScheduleServiceImplTest.java
---
name: 코드 리팩토링
about: (command)EmployeeWorkingPartServiceImpl, (command)WeeklyScheduleServiceImpl DTO -> VO로 변경했습니다.
---
=> ♻️✨ 코드 수정 및 기능 추가: 코드 리팩토링

wizbuddy-schedule-service/build.gradle, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/WizbuddyScheduleServiceApplication.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/config/FeignClientConfig.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartServiceImpl.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/infrastructure/client/UserServiceClient.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/infrastructure/dto/EmployeeDTO.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/infrastructure/dto/WeeklyScheduleDTO.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/infrastructure/service/ScheduleInfraService.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/infrastructure/service/ScheduleInfraServiceImpl.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/query/service/EmployeeWorkingPartServiceImpl.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/command/application/service/WeeklyScheduleServiceImpl.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/query/repository/WeeklyScheduleMapper.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/query/service/WeeklyScheduleService.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/weeklyschedule/query/service/WeeklyScheduleServiceImpl.java, wizbuddy-schedule-service/src/main/resources/com/intbyte/wizbuddy/weeklyschedule/query/repository/WeeklyScheduleMapper.xml
---
name: 기능 추가
about: ScheduleInfraService 추가
---
=> ✨ 기능 추가: ScheduleInfraService 추가

wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/board/command/application/dto/RequestEditManualBoardDTO.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/board/command/application/dto/RequestEditNoticeBoardDTO.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/board/command/domain/entity/vo/response/ResponseUpdateManualBoardVO.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/board/query/dto/ManualBoardDTO.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/application/controller/ManualBoardLikeController.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/application/service/ManualBoardLikedService.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/application/service/NoticeBoardLikedService.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/domain/repository/ManualBoardLikedRepository.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/command/domain/repository/NoticeBoardLikedRepository.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/controller/ManualBoardLikeController.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/controller/NoticeBoardLikeController.java, wizbuddy-shop-service/src/main/resources/com/intbyte/wizbuddy/like/query/repository/ManualBoardLikedMapper.xml, wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/board/command/application/service/ManualBoardServiceTests.java, wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/board/command/application/service/NoticeBoardServiceTests.java, wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/board/query/service/ManualBoardServiceTests.java, wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/board/query/service/NoticeBoardServiceTests.java, wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/command/application/service/ManualBoardServiceLikeTests.java, wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/command/application/service/NoticeBoardServiceLikeTests.java, wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/query/service/ManualBoardServiceLikeTests.java, wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/query/service/NoticeBoardServiceLikeTests.java
---
name: 매뉴얼 게시판, 공지사항 게시판 관련 테스트코드 추가 및 수정
about: 
1. 매뉴얼 게시판, 공지사항 게시판 등록, 수정, 삭제 테스트코드 수정
2. 매뉴얼 게시판, 공지사항 게시판 조회 테스트코드 수정
3. 매뉴얼 게시판, 공지사항 게시판 좋아요 등록, 조회 테스트코드 추가
title: ''
labels: enhancement fix
assignees: ''
---
- 해당 테스트코드가 코드를 잘 테스트하고 있는지
=> ✨ 기능 추가/수정: 매뉴얼 게시판, 공지사항 게시판 관련 테스트코드 추가 및 수정

wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/query/service/ManualBoardServiceLikeTests.java, wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/query/service/NoticeBoardServiceLikeTests.java
---
name: 매뉴얼 게시판, 공지사항 게시판 좋아요 조회 테스트코드 수정
about: 테스트코드에서 println 대신 assertThat 사용하여 테스트할 수 있도록 코드를 수정했습니다.
title: ''
labels: fix
assignees: ''
---
- assertThat을 사용해서 테스트를 진행한 부분
=> ♻️ 코드 수정: 매뉴얼 게시판, 공지사항 게시판 좋아요 조회 테스트코드 수정

wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/dto/RequestEditEmployeeDTO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/dto/RequestEditEmployerDTO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/EmployeeService.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/EmployerService.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/common/exception/GlobalExceptionHandler.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/dto/EmployeeDTO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/dto/EmployerDTO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/dto/UserDTO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/repository/EmployeeMapper.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/repository/EmployerMapper.java, wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/EmployeeMapper.xml, wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/EmployerMapper.xml
=> 코드 수정: DTO에 생성자 어노테이션 재추가 및 basePackage 경로 수정 및 서비스 코드 수정

wizbuddy-user-service/build.gradle, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/controller/UserController.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/EmailVerificationService.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserServiceImpl.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/EmailVerificationVO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/ResponseEmailMessageVO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/common/exception/StatusEnum.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/config/EmailConfig.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/config/RedisConfig.java
추후 테스트 코드 작성 완료
---
name: 기능 개발 이슈
about: 만든 기능 상세히 설명하자
title: ''
assignees: ''
---
- 
- 
-
=> ✨ 기능 추가: 이메일 인증을 위한 Redis 설정 적용 및 추가

wizbuddy-user-service/build.gradle, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/controller/UserController.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserService.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserServiceImpl.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/UserEntity.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/vo/request/RequestRegisterKakaoUserVO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/repository/UserRepository.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/config/AppConfig.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/dto/EmployeeAdditionalDTO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/dto/KakaoUserDTO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/dto/UserDTO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/security/JwtUtil.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/security/WebSecurity.java
---
name: 기능 개발 이슈
about: 만든 기능 상세히 설명하자
title: '카카오 Oauth2.0 로그인 기능 구현'
---
- 인가코드를 받는 코드가 바로 access token 까지 발급받는 코드로 이어지는 점을 봐주시는 것이 좋을 것 같아요!
=> 카카오 Oauth2.0 로그인 기능 구현

wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/client/ScheduleServiceClient.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/dto/WeeklyScheduleDTO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/request/RequestModifyScheduleVO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/request/RequestRegistEmployeeWorkingPartVO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/request/RequestRegistWeeklyScheduleVO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/response/ResponseFindEmployeeWorkingPartVO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/response/ResponseModifyScheduleVO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/response/ResponseRegistEmployeeVO.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/infrastructure/schedule/vo/response/ResponseRegistWeeklyScheduleVO.java
---
name: schedule Infrastructure 수정 및 관련 VO,DTO 추가
about: 추가되지않은 VO, DTO를 추가하고 경로가 잘못되어 import수정했습니다.
---
=> ✨ 기능 추가: userService의 schedule infrastructure 수정 및 관련 VO, DTO 추가

wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/application/service/SubsBoardServiceImpl.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/infrastructure/client/ShopServiceClient.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/infrastructure/dto/ShopDTO.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/infrastructure/event/SubsBoardDeletedEvent.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/infrastructure/event/SubsBoardEventListener.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/infrastructure/service/InfraSubsBoardService.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/command/infrastructure/service/InfraSubsBoardServiceImpl.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/board/infrastructure/service/InfraSubsBoardService.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/application/dto/CommentDTO.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/application/service/CommentServiceImpl.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/domain/aggregate/Comment.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/domain/aggregate/vo/request/RequestInsertCommentVO.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/domain/aggregate/vo/response/ResponseAdoptCommentVO.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/domain/aggregate/vo/response/ResponseInsertCommentVO.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/infrastructure/dto/EmployeePerShopDTO.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/infrastructure/service/InfraCommentService.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/command/infrastructure/service/InfraCommentServiceImpl.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/infrastructure/service/InfraAdoptService.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/query/domain/aggregate/Comment.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/comment/query/domain/aggregate/vo/response/ResponseFindCommentVO.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/common/exception/StatusEnum.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartService.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/application/service/EmployeeWorkingPartServiceImpl.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/infrastructure/service/ScheduleInfraService.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/employeeworkingpart/command/infrastructure/service/ScheduleInfraServiceImpl.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/infrastructure/client/UserServiceClient.java, wizbuddy-schedule-service/src/main/java/com/intbyte/wizbuddy/infrastructure/dto/EmployeeDTO.java, wizbuddy-schedule-service/src/main/resources/com/intbyte/wizbuddy/comment/query/domain/repository/CommentMapper.xml, wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/comment/command/application/service/CommentServiceImplTests.java, wizbuddy-schedule-service/src/test/java/com/intbyte/wizbuddy/comment/infrastructure/service/InfraCommentServiceImplTests.java
---
name: ✨ 기능 수정/추가: FeignClient 기능 수정 및 추가
about: FeignClient 기능 수정 및 추가
title: ''
assignees: ''
---
- [✅ ] 신규 기능
- [✅ ] 기능 수정
- [✅ ] 버그 픽스
-  FeignClient  서버 설정 시 공통 부분은 밖으로 infra폴더 뺏습니다. 오류가 납니다.
- FeignClient 기능 수정 및 추가
=> ✨ 기능 수정/추가: FeignClient 기능 수정 및 추가

wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/infrastructure/UserTypeEnum.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/infrastructure/client/UserServiceClient.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/infrastructure/dto/UserDTO.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/controller/ManualBoardLikeController.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/controller/NoticeBoardLikeController.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/service/ManualBoardLikedService.java, wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/like/query/service/NoticeBoardLikedService.java, wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/query/service/ManualBoardServiceLikeTests.java, wizbuddy-shop-service/src/test/java/com/intbyte/wizbuddy/like/query/service/NoticeBoardServiceLikeTests.java
---
name: ♻️ 코드 수정: 좋아요 조회 시 좋아요 누른 회원 정보 조회하도록 수정
about: 좋아요 정보 조회 시 좋아요 누른 회원 정보를 조회할 수 있도록 코드를 수정했습니다
like 패키지에서도 user service를 사용하기 위해서 infrastructure 패키지를 이동하였습니다.
title: ''
labels: fix
assignees: ''
---
- 해당 코드의 로직이 맞는지 확인해주시면 좋겠습니다
=> ♻️ 코드 수정: 좋아요 조회 시 좋아요 누른 회원 정보 조회하도록 수정

wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/command/application/controller/CheckListController.java, wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/checklist/query/controller/CheckListController.java, wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/command/application/controller/TaskController.java, wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/task/query/controller/TaskController.java, wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/command/application/controller/TaskPerCheckListController.java, wizbuddy-task-service/src/main/java/com/intbyte/wizbuddy/taskperchecklist/query/controller/TaskPerCheckListController.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/security/WebSecurity.java
---
name: 기능 개발 이슈
about: 공통 api requestMapping으로 빼냄
title: ''♻️ 코드 수정: checklist-service api 수정"
assignees: ''
---
- checklist-service controller에서 api 중복되는 부분을 requestMapping으로 뺐습니다.
- 그에 따른 webSecurity를 수정했습니다.
=> ♻️ 코드 수정: checklist-service api 수정

wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/controller/UserController.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserService.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserServiceImpl.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/EmployeeAdditional.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/domain/aggregate/UserTypeEnum.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/repository/EmployeeMapper.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/repository/EmployerMapper.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/repository/UserMapper.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/service/EmployeeService.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/query/service/EmployerService.java, wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/EmployeeMapper.xml, wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/EmployerMapper.xml, wizbuddy-user-service/src/main/resources/com/intbyte/wizbuddy/user/query/repository/UserMapper.xml, wizbuddy-user-service/src/test/java/com/intbyte/wizbuddy/user/command/application/service/EmployeeServiceTests.java, wizbuddy-user-service/src/test/java/com/intbyte/wizbuddy/user/command/application/service/EmployerServiceTests.java
---
name: 기능 개발 이슈
about: 만든 기능 상세히 설명하자
title: '✨ 기능 수정: api test 하면서 추가적으로 수정해야 할 부분 수정
---
`Authentication authentication` 에 대한 내용을 삭제하며 api test하면서 기존의 생기지 않았던 문제들에 대해 해결했습니다.
=> ✨ 기능 수정: api test 하면서 추가적으로 수정해야 할 부분 수정

wizbuddy-shop-service/src/main/java/com/intbyte/wizbuddy/security/WebSecurity.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/command/application/service/UserServiceImpl.java, wizbuddy-user-service/src/main/java/com/intbyte/wizbuddy/user/security/JwtUtil.java
---
name: 기능 개발 이슈
about: 만든 기능 상세히 설명하자
title: '✨ 기능 수정: permitAll이 아닌 특정 권한이 필요한 코드 또한 가능하게 수정'
---
기존에는 api 요청을 할 때 권한이 permitAll()일 때만 가능했지만 그 부분을 수정하였습니다.
이제 UserTypeEnum을 활용해서 할 수 있습니다.
=> ✨ 기능 수정: permitAll이 아닌 특정 권한이 필요한 코드 또한 가능하게 수정
